// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: recoverKV.proto
#ifndef GRPC_recoverKV_2eproto__INCLUDED
#define GRPC_recoverKV_2eproto__INCLUDED

#include "recoverKV.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace recoverKV {

// Defines the service
class RecoverKV final {
 public:
  static constexpr char const* service_full_name() {
    return "recoverKV.RecoverKV";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // Function invoked for fetching value
    virtual ::grpc::Status getValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::recoverKV::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>> AsyncgetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>>(AsyncgetValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>> PrepareAsyncgetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>>(PrepareAsyncgetValueRaw(context, request, cq));
    }
    // Function invoked for fetching value
    virtual ::grpc::Status setValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::recoverKV::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>> AsyncsetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>>(AsyncsetValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>> PrepareAsyncsetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>>(PrepareAsyncsetValueRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // Function invoked for fetching value
      virtual void getValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void getValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void getValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      // Function invoked for fetching value
      virtual void setValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void setValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void setValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>* AsyncgetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>* PrepareAsyncgetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>* AsyncsetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::recoverKV::Response>* PrepareAsyncsetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status getValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::recoverKV::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>> AsyncgetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>>(AsyncgetValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>> PrepareAsyncgetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>>(PrepareAsyncgetValueRaw(context, request, cq));
    }
    ::grpc::Status setValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::recoverKV::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>> AsyncsetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>>(AsyncsetValueRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>> PrepareAsyncsetValue(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>>(PrepareAsyncsetValueRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void getValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void getValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void getValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void setValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void setValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void setValue(::grpc::ClientContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>* AsyncgetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>* PrepareAsyncgetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>* AsyncsetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::recoverKV::Response>* PrepareAsyncsetValueRaw(::grpc::ClientContext* context, const ::recoverKV::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_getValue_;
    const ::grpc::internal::RpcMethod rpcmethod_setValue_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // Function invoked for fetching value
    virtual ::grpc::Status getValue(::grpc::ServerContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response);
    // Function invoked for fetching value
    virtual ::grpc::Status setValue(::grpc::ServerContext* context, const ::recoverKV::Request* request, ::recoverKV::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_getValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_getValue() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_getValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetValue(::grpc::ServerContext* context, ::recoverKV::Request* request, ::grpc::ServerAsyncResponseWriter< ::recoverKV::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_setValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_setValue() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_setValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetValue(::grpc::ServerContext* context, ::recoverKV::Request* request, ::grpc::ServerAsyncResponseWriter< ::recoverKV::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_getValue<WithAsyncMethod_setValue<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_getValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_getValue() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::recoverKV::Request, ::recoverKV::Response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::recoverKV::Request* request, ::recoverKV::Response* response) { return this->getValue(context, request, response); }));}
    void SetMessageAllocatorFor_getValue(
        ::grpc::experimental::MessageAllocator< ::recoverKV::Request, ::recoverKV::Response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::recoverKV::Request, ::recoverKV::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_getValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getValue(
      ::grpc::CallbackServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getValue(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_setValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_setValue() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::recoverKV::Request, ::recoverKV::Response>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::recoverKV::Request* request, ::recoverKV::Response* response) { return this->setValue(context, request, response); }));}
    void SetMessageAllocatorFor_setValue(
        ::grpc::experimental::MessageAllocator< ::recoverKV::Request, ::recoverKV::Response>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::recoverKV::Request, ::recoverKV::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_setValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* setValue(
      ::grpc::CallbackServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* setValue(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_getValue<ExperimentalWithCallbackMethod_setValue<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_getValue<ExperimentalWithCallbackMethod_setValue<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_getValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_getValue() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_getValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_setValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_setValue() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_setValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_getValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_getValue() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_getValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestgetValue(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_setValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_setValue() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_setValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsetValue(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_getValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_getValue() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->getValue(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_getValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status getValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* getValue(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* getValue(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_setValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_setValue() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->setValue(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_setValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status setValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* setValue(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* setValue(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_getValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_getValue() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::recoverKV::Request, ::recoverKV::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::recoverKV::Request, ::recoverKV::Response>* streamer) {
                       return this->StreamedgetValue(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_getValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status getValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedgetValue(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::recoverKV::Request,::recoverKV::Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_setValue : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_setValue() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::recoverKV::Request, ::recoverKV::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::recoverKV::Request, ::recoverKV::Response>* streamer) {
                       return this->StreamedsetValue(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_setValue() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status setValue(::grpc::ServerContext* /*context*/, const ::recoverKV::Request* /*request*/, ::recoverKV::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsetValue(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::recoverKV::Request,::recoverKV::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_getValue<WithStreamedUnaryMethod_setValue<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_getValue<WithStreamedUnaryMethod_setValue<Service > > StreamedService;
};

}  // namespace recoverKV


#endif  // GRPC_recoverKV_2eproto__INCLUDED
